"""initial schema

Revision ID: c190bb280894
Revises: 
Create Date: 2026-09-14 23:06:04.384866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c190bb280894'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upi_id', sa.String(length=64), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('ifsc_code', sa.String(length=16), nullable=False),
    sa.Column('owner_name', sa.String(length=128), nullable=False),
    sa.Column('bank_name', sa.String(length=128), nullable=False),
    sa.Column('account_type', sa.Enum('INDIVIDUAL', 'MERCHANT', name='account_type'), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('true_label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_device_id'), 'accounts', ['device_id'], unique=False)
    op.create_index(op.f('ix_accounts_true_label'), 'accounts', ['true_label'], unique=False)
    op.create_index(op.f('ix_accounts_upi_id'), 'accounts', ['upi_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_account_id', sa.Integer(), nullable=False),
    sa.Column('receiver_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='transaction_status'), nullable=False),
    sa.Column('true_label', sa.String(length=64), nullable=True),
    sa.Column('scenario', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_transactions_receiver_account_id'), 'transactions', ['receiver_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_scenario'), 'transactions', ['scenario'], unique=False)
    op.create_index(op.f('ix_transactions_sender_account_id'), 'transactions', ['sender_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_true_label'), 'transactions', ['true_label'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'ESCALATED', 'CLOSED', name='case_status'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='case_severity'), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_transaction_id'), 'cases', ['transaction_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_account_id', sa.Integer(), nullable=False),
    sa.Column('target_account_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.Enum('TRANSACTION', 'SHARED_DEVICE', 'REPEATED_COUNTERPARTY', name='graph_edge_type'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_edge_type'), 'graph_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_account_id'), 'graph_edges', ['source_account_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_account_id'), 'graph_edges', ['target_account_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_transaction_id'), 'graph_edges', ['transaction_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('graph_score', sa.Float(), nullable=True),
    sa.Column('fused_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('intervention_level', sa.Enum('INFORM', 'WARN', 'VERIFY', 'HOLD', 'RESTRICT', 'ESCALATE', name='intervention_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_transaction_id'), 'risk_scores', ['transaction_id'], unique=True)
    op.create_table('case_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_table('reason_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('RULE', 'ML', 'GRAPH', name='reason_code_source'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('template', sa.String(length=512), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reason_codes_code'), 'reason_codes', ['code'], unique=False)
    op.create_index(op.f('ix_reason_codes_risk_score_id'), 'reason_codes', ['risk_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reason_codes_risk_score_id'), table_name='reason_codes')
    op.drop_index(op.f('ix_reason_codes_code'), table_name='reason_codes')
    op.drop_table('reason_codes')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_risk_scores_transaction_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_graph_edges_transaction_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_target_account_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_account_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_edge_type'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_cases_transaction_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_transactions_true_label'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_sender_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_scenario'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_accounts_upi_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_true_label'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_device_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
